version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install uv
    install:
      - uv sync --locked --only-group docs --active

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# python:
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs
