name: lint

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        versions:
          - 66
        python-version:
          - "3.12"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install vapoursynth-portable==${{ matrix.versions }}
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Running ruff
        continue-on-error: true
        run: ruff check svsfunc

      - name: Running mypy
        run: mypy svsfunc
